/* date = January 8th 2021 11:05 pm */

#ifndef WIN32_MAIN_H
#define WIN32_MAIN_H

#include "utils.h"

//~ NOTE(Jai): Recursive macro definition only for 
// editor syntax highlighting
#define DWORD DWORD
#define FILETIME FILETIME
#define HMODULE HMODULE
#define HANDLE HANDLE
#define BITMAPINFO BITMAPINFO
#define HDC HDC
#define LARGE_INTEGER LARGE_INTEGER
#define XINPUT_STATE XINPUT_STATE
#define LONG LONG
#define SHORT SHORT
#define LPVOID LPVOID
#define HINSTANCE HINSTANCE
#define PSTR PSTR
#define HRESULT HRESULT
#define LPCGUID LPCGUID
#define LPUNKNOWN LPUNKNOWN
#define XINPUT_VIBRATION XINPUT_VIBRATION
#define WIN32_FIND_DATAA WIN32_FIND_DATAA
#define WIN32_FILE_ATTRIBUTE_DATA WIN32_FILE_ATTRIBUTE_DATA
#define LPDIRECTSOUNDBUFFER LPDIRECTSOUNDBUFFER
#define DSBUFFERDESC DSBUFFERDESC
#define WAVEFORMATEX WAVEFORMATEX
#define LPDIRECTSOUND LPDIRECTSOUND
#define MSG MSG
#define HCURSOR HCURSOR
#define PAINTSTRUCT PAINTSTRUCT
#define MONITORINFO MONITORINFO
#define LPARAM LPARAM
#define WINDOWPLACEMENT WINDOWPLACEMENT
#define WPARAM WPARAM
#define UINT UINT
#define HWND HWND
#define LRESULT LRESULT
#define SIZE_T SIZE_T
#define WNDCLASSA WNDCLASSA
#define INT INT
#define WNDPROC WNDPROC
#define HMENU HMENU
#define LPDWORD LPDWORD
#define RECT RECT
#define LONG_PTR LONG_PTR
#define LPSECURITY_ATTRIBUTES LPSECURITY_ATTRIBUTES
#define LPOVERLAPPED LPOVERLAPPED
#define IDWriteFactory IDWriteFactory
#define IUnknown IUnknown
#define DWRITE_FACTORY_TYPE_SHARED DWRITE_FACTORY_TYPE_SHARED
#define ID2D1Factory ID2D1Factory
#define D2D1_FACTORY_TYPE_MULTI_THREADED D2D1_FACTORY_TYPE_MULTI_THREADED
#define HBRUSH HBRUSH

#endif //WIN32_MAIN_H
